/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.weberamaral.samples.application

import com.github.weberamaral.samples.dataprovider.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
