/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.weberamaral.samples.application

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
